GluuFederation/community-edition-setup

- templates/oxauth-config.json
WhiteList / Blacklist redirect_uri's
> oxAuth #301

- templates/oxauth-config.json
oxAuth #363
Dynamic Client Registration Scope Not Restricted / Sub Type: Pairwise
> oxAuth #363 Dynamic Client Registration Scope Not Restricted / Sub Type: Pairwise

- setup.py
- templates/passport.ldif
Please check the pull request.
> passportConfiguration

- static/scripts/export24.py
- static/scripts/import244.py
just made default N visible for Is Shibboleth SAML IDP installed? (y/N):n
> export244.py minor fix, import244.py systemd check

- setup.py
- templates/jetty/identity_web_resources.xml
- templates/jetty/oxauth_web_resources.xml
This pull request is related with [issue/365](https://github.com/GluuFederation/oxAuth/issues/365): 
- added configuration for static content deployment in oxauth and identity projects
> oxAuth: Issue #365

- setup.py
- templates/jetty/identity_web_resources.xml
- templates/jetty/oxauth_web_resources.xml
- splited static resources and custom pages to a different directories
> External resources

- static/openldap/gluu.schema
- templates/appliance.ldif
- added oxMemcachedConfiguration attribute in gluuAppliance
> oxAuth. Issue 467

- schema/gluu_schema.json
- static/opendj/deprecated/101-ox.ldif
- static/openldap/gluu.schema
- templates/appliance.ldif
- auto generated oxMemcachedConfiguration attribute
- updated appliance.ldif
> oxAuth. Issue:467

- templates/oxauth-config.json
Remove validate_token_endpoint
> oxAuth #510

- templates/oxauth-config.json
Security error thrown using implicit flow when request the userinfo endpoint
> oxAuth #529

- schema/gluu_schema.json
- static/opendj/deprecated/101-ox.ldif
- static/openldap/gluu.schema
Related with [this issue](https://github.com/GluuFederation/oxTrust/issues/522).
> - added oxLogConfigLocation in gluuAppliance schema

- templates/oxauth-config.json
> oxAuth #577

- static/scripts/convert_client.py
- templates/clients.ldif
- templates/oxauth-config.json
- templates/test/oxauth/data/oxauth-test-data.ldif
oxAuth #525
Enforce Grant Type Client Restrictions
> Enforce grant type client restrictions

- schema/gluu_schema.json
Resolve oxTrust#324 - Added random key for person
> Add Random key for user regisration

- schema/gluu_schema.json
- static/opendj/deprecated/101-ox.ldif
- static/openldap/gluu.schema
Related with [issue_645](https://github.com/GluuFederation/oxTrust/issues/645) and [issue_603](https://github.com/GluuFederation/oxAuth/issues/603)
> - added oxRefreshTokenLifetime field to Client model

- schema/gluu_schema.json
- templates/oxauth-config.json
Add real session state support
> oxAuth #592

- templates/oxauth-config.json
oxAuth Configurations for oxAuth#526 & oxAuth#527
> Update Grant Type Configuration #526 & #527

- schema/gluu_schema.json
- static/opendj/deprecated/101-ox.ldif
- static/openldap/gluu.schema
Related with [this issue](https://github.com/GluuFederation/oxAuth/issues/228).
> - added nickname field to U2F device registration entry

- templates/scripts.ldif
updated android/ios download properties for super gluu
> Update scripts.ldif for android/ios download properties for super gluu

- static/scripts/export3031.py
Upgrade script will be require 
1) wget -c https://raw.githubusercontent.com/GluuFederation/community-edition-setup/master/ldif.py
2)  python-pip and  jsonmerge
> new export Script for exporting data from 3.0 to 3.1

- static/scripts/export3031.py
- static/scripts/import3031.py
bug fix - https://github.com/GluuFederation/community-edition-setup/issues/336
> Upgrade script 3.1

- schema/gluu_schema.json
- static/opendj/deprecated/101-ox.ldif
- static/openldap/gluu.schema
- static/oxauth/oxauth-errors.json
Related with [this](https://github.com/GluuFederation/oxAuth/issues/612) and [this](https://github.com/GluuFederation/oxTrust/issues/649) issues.
> - added disable field into client

- static/scripts/export2431.py
- static/scripts/import2431.py
- static/scripts/import3031.py
> Changes for 3.1.1 beta

- templates/attributes.ldif
Only first value of multi-valued claim is returned in id_token
> OpenID Connect Provider Certification

- static/scripts/export2431.py
- static/scripts/export3031.py
- static/scripts/import3031.py
update for 3031 upgrade script (Cr related changes)
> CR related changes

- templates/attributes.ldif
- templates/oxtrust-import-person.json
added user status to ox-trust-person.json
> oxTrust#757

- static/scripts/export2431.py
`User status` Attribute display name issue resolved
> `User status` Attribute display name issue resolved

- schema/gluu_schema.json
Restrict requesting claims individually
> oxAuth #812

- static/scripts/openldap2opendj_migration/README.md
@mbaser, here's my review on your file.
Thanks for reaching out!
> Grammar and formatting

- static/radius/templates/gluu_radius.ldif
* additions/modification to the radius template file
> Changes in this commit:

- static/radius/etc/gluu/conf/radius/gluu-radius.properties
* Fixed `gluu-radius.properties` values
> Pull request from Rolain Djeumen

- templates/attributes.ldif
Related to this issue: https://github.com/GluuFederation/oxTrust/issues/1958
> Added CIBA attributes to the attributes.ldif template

- schema/gluu_schema.json
- static/opendj/101-ox.ldif
#477 - Add persistence manager support from oxcore
https://github.com/GluuFederation/oxd/issues/477
> #477 - Add persistence manager support from oxcore

- schema/gluu_schema.json
- static/opendj/101-ox.ldif
Related to this issue: https://github.com/GluuFederation/oxAuth/issues/1370
> New scope attribute to publish or not in discovery endpoint

- schema/gluu_schema.json
- static/opendj/101-ox.ldif
Reverts GluuFederation/community-edition-setup#680
> Revert "New scope attribute to publish or not in discovery endpoint"

- static/extension/ciba/end_user_notification.py
- templates/scripts.ldif
@mbaser Please could you take a look to this implementation, the target is to have a default interception script already added in the DB when Gluu Server is installed. Thanks in advance.
> Added default CIBA interception script.

- templates/https_gluu.conf
Config needed to get Firebase working with push notifications.
> Added apache config needed to publish Firebase config file in the root.

- templates/apache/https_gluu.conf
- templates/oxauth/oxauth-config.json
Issue: https://github.com/GluuFederation/oxAuth/issues/141
> Device authorization grant type

- static/extension/person_authentication/PassportExternalAuthenticator.py
related to oxAuth issue https://github.com/GluuFederation/oxAuth/issues/1448
> fix: update passport social script to handle provider config state problem 

- static/extension/person_authentication/PassportExternalAuthenticator.py
- static/extension/person_authentication/SamlPassportAuthenticator.py
Only Passport social and SAML script changes. 
PR merged for oxAuth https://github.com/GluuFederation/oxAuth/pull/1483
> fix: update jwt date check function in passport scripts 

- static/rdbm/sql_data_types.json
https://github.com/GluuFederation/community-edition-setup/issues/766
> fix: the size of oxAuthUmaScope column in oxUmaResourcePermission and oxUmaResource should be increased in mysql #766

- templates/oxauth/oxauth-config.json
Issue: https://github.com/GluuFederation/oxAuth/issues/1561
> Added flag to toogle autofix for grant types and response types

- gluu_install.py
- setup.py
- setup_app/installers/opendj.py
- setup_app/test_data_loader.py
- setup_app/utils/properties_utils.py
Commits within this PR fixes setup issues after refactoring
> Disa refactor fixes

- setup_app/test_data_loader.py
- setup_app/utils/crypto64.py
> fix: keystore type

- gluu_install.py
- setup_app/installers/fido.py
As described in https://github.com/GluuFederation/fido2/issues/20
> fix: fido external files

- setup.py
- setup_app/installers/gluu.py
- setup_app/utils/arg_parser.py
- setup_app/utils/db_utils.py
Thes options of setup works both pre-setup and post-setup.
> feat:  -ox-trust-authentication-mode -ox-authentication-mode -enable-script

- templates/oxauth/oxauth-config.json
- templates/oxauth/oxauth-config.json.disa-stig
https://github.com/JanssenProject/jans/issues/1503
> feat(community-edition-setup): added localhost to requestUriBlackList

- templates/oxauth/oxauth-config.json
- templates/oxauth/oxauth-config.json.disa-stig
chore(community-edition-setup): requestUriBlackList -> requestUriBlockList
https://github.com/JanssenProject/jans/issues/1503
> chore(community-edition-setup): requestUriBlackList -> requestUriBlockList

- setup_app/installers/couchbase.py
- setup_app/installers/oxtrust.py
- setup_app/installers/passport.py
- setup_app/installers/scim.py
- setup_app/utils/collect_properties.py
Closes https://github.com/GluuFederation/community-edition-setup/issues/901
> fix: random keystore password

- templates/oxtrust/oxtrust_api_clients.ldif
closes https://github.com/GluuFederation/community-edition-setup/issues/905
> fix: rename 'API Resource Server Client' as 'oxTrust API UMA RS'

- setup_app/installers/oxtrust.py
- templates/oxtrust/oxtrust-config.json
https://github.com/GluuFederation/oxTrust/issues/2226
> feat: added oxTrustAdminUIlocalesSupported property to make locale configurable

- setup_app/installers/couchbase.py
Reflection of https://github.com/JanssenProject/jans/issues/2329
> fix: cb 7.1.1 installation

- setup_app/installers/rdbm.py
- setup_app/utils/arg_parser.py
- setup_app/utils/collect_properties.py
> feat: option reset-rdbm-db

- setup_app/data/package_list.json
python3-psycopg2 should be in `package_list.json`
> fix: dependency python3-psycopg2

- docs/README.md
- pylib/package_list.json
- setup.py
- setup_app/data/package_list.json
- setup_app/installers/gluu.py
- setup_app/installers/httpd.py
- setup_app/installers/jetty.py
- setup_app/installers/jre.py
- setup_app/installers/jython.py
- setup_app/installers/node.py
- setup_app/installers/radius.py
- setup_app/static.py
- setup_app/utils/package_utils.py
Reflection of https://github.com/JanssenProject/jans/issues/2521
> Typo setup

- setup.py
> fix: post-setup install service

- gluu_install.py
- setup_app/config.py
- setup_app/installers/couchbase.py
- setup_app/installers/jetty.py
- setup_app/installers/rdbm.py
> feat: Install CB/Spanner DB libraries from separated archive

- templates/oxtrust/oxtrust-config.json
https://github.com/GluuFederation/oxTrust/issues/2225
> feat(oxtrust-server) : Remove files in /var/gluu/identity/removed

- setup_app/installers/rdbm.py
- templates/gluu-mysql.properties
> feat: uniqe constraint for uid in gluuPerson (pgsql/mysql/spanner)

- setup_app/installers/saml.py
- templates/idp/datasource.properties.sql
> fix: JDBC driver class in SAML IDP for postgresql (ref: #946)

- setup_app/installers/casa.py
- setup_app/installers/fido.py
- setup_app/installers/jetty.py
- setup_app/installers/oxauth.py
- setup_app/installers/saml.py
- setup_app/installers/scim.py
> feat: jetty-10 is default

- setup_app/setup_options.py
- setup_app/utils/arg_parser.py
- setup_app/utils/properties_utils.py
> feat: provide all non-named properties via argument -properties

- setup_app/messages.py
Change oauth description as suggested by @nynymike
> fix: oauth description

- setup_app/installers/rdbm.py
- setup_app/utils/package_utils.py
- setup_app/utils/setup_utils.py
Pstgresql installation fixes for centos/rhel
> fix: pgsql fixes for centos/rhel

- gluu_install.py
Reflection of https://github.com/JanssenProject/jans/issues/3620
> fix: downgrade pyjwt for py3.6

- setup_app/installers/rdbm.py
- setup_app/utils/collect_properties.py
> fix: post-setup rdbm installs

- templates/jetty/casa
Closes https://github.com/GluuFederation/casa/issues/254
> feat: pass env var for location of casa administrable file

- setup_app/config.py
- setup_app/installers/base.py
- setup_app/installers/couchbase.py
- setup_app/installers/opendj.py
- setup_app/installers/rdbm.py
- templates/systemd/fido2.service
- templates/systemd/oxauth.service
> fix: start oxauth after db backend

- schema/gluu_schema.json
Reflection of https://github.com/JanssenProject/jans/issues/4058
> fix: typo - remove attribute county

- setup_app/installers/gluu.py
- templates/scan/scan_creds.json
> feat: passwurd keystore with custom password

- tools/key_regeneration/key_regeneration.py
> fix(key-regeneration): check store type from config

- setup_app/installers/rdbm.py
- setup_app/utils/db_utils.py
> fix: maridb json columns with json_valid() constaint

- templates/scopes.ldif
> fix: type of jans_stat is oauth

- setup.py
- setup_app/installers/gluu.py
- setup_app/utils/properties_utils.py
> feat: post setup generate passwurd keystore

- gluu_install.py
> feat: maven user and password as argument

- schema/gluu_schema.json
https://github.com/GluuFederation/oxTrust/issues/2341
> fix(oxtrust-server): oxAuthClient.oxClaimRedirectURI multivalued

- templates/scopes.ldif
feat(community-edition-setup): made jans_stat a default oauth scope #996
https://github.com/GluuFederation/community-edition-setup/issues/996
> feat(community-edition-setup): made jans_stat a default oauth scope #996

- setup_app/utils/db_utils.py
> fix: test data loading with mysql

- gluu_install.py
- install.py
- setup.py
- setup_app/data/package_list.json
> feat: support for EL 9

- setup_app/utils/db_utils.py
> fix: spanner-rest client

- setup_app/utils/tui.py
> fix: replace solo with agama in marketing strings

- static/rdbm/sql_data_types.json
> fix: length of gluuHostname

- templates/idp/oxidp.ldif
ported from version_4.5.0
Signed-off-by: Rolain Djeumen <uprightech@gmail.com>
> feat: added on demand mfa saml acr for shibboleth idp

- tools/key_regeneration/key_regeneration.py
> fix: keygenerator for mysql

- setup_app/utils/printVersion.py
> fix: modification date of MANIFEST.MF in war file is build date

- tools/cache_cleaning/clean_tokens.py
A tool for cleaning caches manually was pushed
> feat: cache cleaning script

- gluu_install.py
> fix: setup version 4.5.4

- setup_app/installers/rdbm.py
- setup_app/utils/setup_utils.py
Fix spanner backend installation
> fix: spanner client

- templates/oxauth/oxauth-errors.json
fix(community-edition-setup): added new error descriptions
https://github.com/GluuFederation/oxAuth/issues/1891
> fix(community-edition-setup): added new error descriptions

- static/rdbm/sql_data_types.json
> fix: duplicated-rdbm-types

- templates/jetty/casa
> fix: casa default file

- gluu_install.py
> fix: check if certs dir exist before create

- schema/gluu_schema.json
- setup_app/installers/fido.py
- templates/apache/https_gluu.conf
- templates/fido2/fido2-errors.json
- templates/fido2/fido2.ldif
Signed-off-by: Yuriy Movchan <Yuriy.Movchan@gmail.com>
> feat(fido2): add fido2 conf error
