static/opendj/opendj_index.json

While working on an "single user" setup to allow installation on our gentoo environment with multiple websites and vhosts. The creation of this index failed. I've added the backend and now it creates the index alright.

cherry pick only opendj_index.json

---

setup.py

This pull request modifies setup.py for better openssl compatibility.
1. OpenSSL itself does not enforce 2-letter state / provinces, and this is not applicable outside the US. The length check for the state was removed.
2. The subject name produced in the self-signed certificate was rearranged to be in 'Reverse RDN order' according to RFC4514. If the subject name is not in this order, openssl may not be able to find the self-signed certificates in the trust chain in Linux, even if they were already installed using update-ca-certificates (debian) or update-ca-trust (red hat)

Openssl compat

---

templates/https_gluu.conf

In reference to: https://support.gluu.org/integrations/opiframe-javascript-produces-unverifiable-session_state-2419#at8012
In OpenID Connect Session Management (https://openid.net/specs/openid-connect-session-1_0.html#OPiframe), the OP provides a check session URL that presents a javascript that listens for login session state changes. In oxAuth, the opiframe performs session state changes by comparing the RP's session_state with the server-side session state set by the "opbs" cookie. The check session iframe attempts to retrieve the contents of the opbs cookie using javascript, however, it cannot access the cookie due to it being set HttpOnly in the Gluu apache server.
This pull request updates the apache configuration so that the opbs cookie is NOT set to HttpOnly and so can be reached …

Do not set the opiframe cookie as HttpOnly so that scripts can access it

---

templates/oxauth-config.json

Add an oxAuth config param for Pairwise ID Type - oxAuth #119

Add an oxAuth config param for Pairwise ID Type - oxAuth #119

---

setup.py

This PR prevents setup process break if OpenLdap dist file is not present during setup process.  
Notice that this is the only case in setup script that `raises` an error. all other functions kindly use `logIt` and allow setup process to continue.  
Also there is a typo in log and `directory` should be changed to `openLdapDistFolder` 
This will help a lot in conditions that package is already installed on system  :)

Don't raise exceptions if openLdap dist not exists

---

setup.py
templates/oxtrust-config.json

During initial setup `ldap_hostname` is always set to `localhost` thus we cannot login after unless manually edit this from ldap server configurations.
This PR honers  `ldap_hostname` & `ldaps_port` configuration variables to fix that.
Also please note that default value for `ldap_hostname` is `localhost` so this is a non-breaking enhancement :)

allow change ldap_hostname

---

templates/https_gluu.conf

"X-Frame-Options" header set by Apache prevents opiframe from being used by RP
oxAuth #541
CORS filter doesn't seem to process pre-flight requests in CE 3.0.x

oxAuth #543

---

templates/oxauth-config.json

Invalid "scopes" field in Dynamic Client Registration request and response

oxAuth #700

---

templates/oxauth-config.json

Add a config value to allow to share the same sub between two Clients with the same sector identifier
https://github.com/GluuFederation/oxAuth/issues/1063

oxAuth #1063

---

setup.py

The Gluu CE containers on Ubuntu and CentOS seem to have different linux `umask` settings , and when the `radius` installation directory is created , it's created on CentOS with very restrictive flags which prevent `oxTrust` from reading the directory, and therefore wrongly claiming radius isn't installed. 
The fix is to explicitly set an appropriate mask to the radius installation directory.

Fix permission issues related to Radius install directory

---

templates/node/passport

after https://github.com/GluuFederation/gluu-passport/pull/87 to run passport `NODE_ENV` needs to be `production`

add NODE_ENV=production to passport conf file

---

templates/node/passport

Adjusting passport env for new config.
- `NODE_BASE` changed to  `/passport`. (`/passport/server` would be something like saying that `src` is home.)
- `NODE_CONFIG_DIR = ${NODE_BASE}/config` , config files are in `/config`
- `NODE_APP=server/app.js` - here the suggested approach would be running `npm start` and not using `node server/app.js`, but this would envolve editing passport shell script and I'm not familiar with it, gonna raise issue.
- removed `NODE_CONFIG_DIR=$NODE_BASE` from `NODE_OPTIONS` because config dir is now setted on env.

passport conf env updates

---

templates/oxauth/oxauth-config.json

1. Flag to filter claims in IdToken
2. Flag to define whether OP will validate hash or not using request_uri param.
https://github.com/GluuFederation/oxAuth/issues/1429

New oxAuth json properties

---

templates/oxauth/oxauth-config.json

fix(community-edition-setup): added missed PS* algs to oxauth-config.json

fix(community-edition-setup): added missed PS* algs to oxauth-config.json

---

templates/oxtrust/oxtrust-config.json

As described in https://github.com/GluuFederation/community-edition-setup/issues/874

fix: cacert path in oxtrust config (ref: #874)

---

gluu_install.py

Remove apache config files when uninstall as described in https://github.com/GluuFederation/community-edition-setup/issues/892

fix: remove apache config when uninstall 

---

templates/oxauth/oxauth-config.json

https://github.com/GluuFederation/oxTrust/issues/2226 Applied quick fix to remove unsupported locale from the list.

Oxtrust issue 2226

---

setup_app/installers/fido.py

@maduvena's note:
_there’s a file in /etc/gluu/conf/fido2/mds/cert which should not be there._

fix: remove metadata-root-ca.cer

---

static/rdbm/sql_data_types.json

closes #930
After this fix:
```
mysql>  show columns in oxDocument where Field = 'document';
+----------+------+------+-----+---------+-------+
| Field    | Type | Null | Key | Default | Extra |
+----------+------+------+-----+---------+-------+
| document | text | YES  |     | NULL    |       |
+----------+------+------+-----+---------+-------+
1 row in set (0.01 sec)
```

fix: column type of oxDocument.document is TEXT

---

setup_app/installers/couchbase.py
setup_app/installers/jetty.py
setup_app/installers/rdbm.py
setup_app/utils/setup_utils.py
templates/jetty/default_webcontext.xml

Fixes issue for #937
1) chown jetty:gluu /opt/gluu/jetty/common
2) Add `default_webcontext.xml` to use if there is no webcontext file for service

fix: cb spanner libraries separated fixes

---

setup_app/utils/tui.py

When DB is Spanner, we should not offer installing IDP for post-setup

fix: disable IDP in post form installation for spanner db

---

setup_app/installers/opendj.py

This fix has been developed by follow reason:
- if we use follow install options:  **-profile=DISA-STIG** and **-opendj-keystore-type=pkcs11**, follow property file is generated: **opendj-setup.properties.pkcs11**:
```
...
keyStorePasswordFile            =/root/.keystore.pin
...
```
Db **sql:/etc/pki/nssdb**, that is used for saving **pkcs11** certificates, doesn't need a password, so we don't create: **/root/.keystore.pin**. In this case opendj setup is down.
This issue can be resolved, creating file **/root/.keystore.pin**, that contains some random text.

fix: fixing of the bug: opendj + pkcs11;

---

templates/oxauth/oxauth-config.json

Added new configuration `return200OnClientRegistration` with default value in `true`
https://github.com/GluuFederation/oxAuth/issues/1780

Change response status 200 (Ok) by 201 (Created) for Client Registration

---

templates/oxauth/oxauth-config.json

New date formatting settings have been added, but start without data to support backward compatibility.
https://github.com/GluuFederation/oxAuth/issues/1789

Feature: Added new settings for date formatting

---

templates/oxauth/oxauth-config.json
templates/oxauth/oxauth-config.json.disa-stig

fix(setup): set errorHandlingMethod=remote and increased sessionIdUnauthenticatedUnusedLifetime
https://github.com/GluuFederation/oxAuth/issues/1818

fix(setup): set errorHandlingMethod=remote and increased sessionIdUnauthenticatedUnusedLifetime

---

static/rdbm/sql_data_types.json

Spanner data type for attribute **document** was missing

fix: spanner data type for document

---

static/rdbm/sql_data_types.json

This PR is related to https://github.com/GluuFederation/oxTrust/issues/2341
All multivalued attributes are JSON if not explicitly defined in `static/rdbm/sql_data_types.json`, We have to remove `oxClaimRedirectURI` form `sql_data_types.json`

fix: remove oxClaimRedirectURI from sql_data_types.json to make it JSON

---

setup_app/test_data_loader.py

fix(community-edition-setup): opPolicyUri is not set in test data which leads to ConfigurationRestWebServiceHttpTest failure #1035

fix(community-edition-setup): opPolicyUri is not set in test data which leads to ConfigurationRestWebServiceHttpTest failure #1035
